"""rename department

Revision ID: 32a3fb0e5e8e
Revises: d7277585f757
Create Date: 2024-02-05 14:53:43.811362

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '32a3fb0e5e8e'
down_revision = 'd7277585f757'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('department', 'departments')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('departments', 'department')
    # ### end Alembic commands ###
