"""rename address

Revision ID: 828d3d88fcf7
Revises: 32a3fb0e5e8e
Create Date: 2024-02-05 14:58:09.612399

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '828d3d88fcf7'
down_revision = '32a3fb0e5e8e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('departments', 'address',  new_column_name='location')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('departments', 'location',  new_column_name='address')

    # ### end Alembic commands ###
